version: 2
updates:
  # Frontend React application dependencies
  - package-ecosystem: "npm"
    directory: "/src/web"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "frontend"
    reviewers:
      - "team-frontend"
    groups:
      react:
        patterns:
          - "react*"
          - "@types/react*"
      mui:
        patterns:
          - "@mui/*"

  # API Gateway Node.js dependencies
  - package-ecosystem: "npm"
    directory: "/src/backend/api-gateway"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    versioning-strategy: "auto"
    allow:
      - dependency-type: "production"
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(deps-dev)"
      include: "scope"
    labels:
      - "dependencies"
      - "api-gateway"
    reviewers:
      - "team-backend"

  # Analytics Service Python dependencies
  - package-ecosystem: "pip"
    directory: "/src/backend/analytics-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "analytics-service"
    reviewers:
      - "team-backend"

  # Contact Service Python dependencies
  - package-ecosystem: "pip"
    directory: "/src/backend/contact-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "contact-service"
    reviewers:
      - "team-backend"

  # Message Service Go dependencies
  - package-ecosystem: "gomod"
    directory: "/src/backend/message-service"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "message-service"
    reviewers:
      - "team-backend"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "team-devops"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    labels:
      - "dependencies"
      - "ci-cd"
    reviewers:
      - "team-devops"