# Kubernetes ConfigMap manifest v1
# Version: 1.0.0
# Purpose: Centralized configuration for WhatsApp Web Enhancement Application microservices
# Dependencies: k8s.io/api/core v1

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: analytics-service-config
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: analytics-service
    version: v1
    managed-by: kustomize
data:
  # Server Configuration
  PORT: "8000"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Monitoring Configuration
  METRICS_PATH: "/metrics"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8081"
  
  # Database Configuration
  POSTGRES_HOST: "postgres-analytics"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "analytics"
  POSTGRES_MAX_CONNECTIONS: "100"
  
  # Cache Configuration
  REDIS_HOST: "redis-analytics"
  REDIS_PORT: "6379"
  REDIS_MAX_CONNECTIONS: "50"
  REDIS_TIMEOUT: "5000"
  
  # API Rate Limiting
  API_RATE_LIMIT: "1000"
  API_RATE_WINDOW: "60"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-service-config
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: message-service
    version: v1
    managed-by: kustomize
data:
  # Server Configuration
  HTTP_PORT: "8080"
  GRPC_PORT: "9000"
  METRICS_PORT: "9090"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Monitoring Configuration
  METRICS_PATH: "/metrics"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8081"
  
  # Redis Configuration
  REDIS_HOST: "redis-message"
  REDIS_PORT: "6379"
  REDIS_MAX_CONNECTIONS: "100"
  REDIS_TIMEOUT: "5000"
  
  # MongoDB Configuration
  MONGO_HOST: "mongo-message"
  MONGO_PORT: "27017"
  MONGO_DB: "messages"
  MONGO_MAX_POOL_SIZE: "100"
  MONGO_TIMEOUT: "5000"
  
  # Message Processing Configuration
  MESSAGE_BATCH_SIZE: "1000"
  MESSAGE_PROCESSING_TIMEOUT: "30000"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: template-service-config
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: template-service
    version: v1
    managed-by: kustomize
data:
  # Server Configuration
  PORT: "3000"
  LOG_LEVEL: "info"
  LOG_FORMAT: "json"
  
  # Monitoring Configuration
  METRICS_PATH: "/metrics"
  METRICS_PORT: "9090"
  HEALTH_CHECK_PATH: "/health"
  HEALTH_CHECK_PORT: "8081"
  
  # Database Configuration
  POSTGRES_HOST: "postgres-template"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "templates"
  POSTGRES_MAX_CONNECTIONS: "50"
  
  # Cache Configuration
  REDIS_HOST: "redis-template"
  REDIS_PORT: "6379"
  REDIS_MAX_CONNECTIONS: "30"
  REDIS_TIMEOUT: "5000"
  
  # Template Management Configuration
  TEMPLATE_CACHE_TTL: "3600"
  TEMPLATE_MAX_SIZE: "65536"