# Kubernetes Secrets manifest for WhatsApp Web Enhancement Application
# Version: v1
# This file contains sensitive configuration data and should be handled with extreme care
# Ensure all secret values are properly base64 encoded before deployment

---
apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secrets
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: api-gateway
    managed-by: kustomize
  annotations:
    encryption.kubernetes.io/v1: aescbc # Ensures secrets are encrypted at rest
    vault.hashicorp.com/agent-inject: "true" # Optional: For HashiCorp Vault integration
type: Opaque
data:
  # Authentication secrets for API Gateway
  JWT_SECRET: ${BASE64_JWT_SECRET}
  
  # Auth0 integration credentials
  AUTH0_CLIENT_SECRET: ${BASE64_AUTH0_CLIENT_SECRET}
  AUTH0_API_KEY: ${BASE64_AUTH0_API_KEY}
  AUTH0_DOMAIN: ${BASE64_AUTH0_DOMAIN}
  
  # Encryption keys for sensitive data
  API_ENCRYPTION_KEY: ${BASE64_API_ENCRYPTION_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: message-service-secrets
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: message-service
    managed-by: kustomize
  annotations:
    encryption.kubernetes.io/v1: aescbc
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # WhatsApp Business API credentials
  WHATSAPP_API_TOKEN: ${BASE64_WHATSAPP_API_TOKEN}
  WHATSAPP_WEBHOOK_SECRET: ${BASE64_WHATSAPP_WEBHOOK_SECRET}
  WHATSAPP_BUSINESS_ID: ${BASE64_WHATSAPP_BUSINESS_ID}
  
  # Redis credentials for message queue
  REDIS_PASSWORD: ${BASE64_REDIS_PASSWORD}
  
  # Message encryption keys
  MESSAGE_ENCRYPTION_KEY: ${BASE64_MESSAGE_ENCRYPTION_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: contact-service-secrets
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: contact-service
    managed-by: kustomize
  annotations:
    encryption.kubernetes.io/v1: aescbc
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # Database credentials
  POSTGRES_PASSWORD: ${BASE64_POSTGRES_PASSWORD}
  
  # Contact data encryption keys
  CONTACT_ENCRYPTION_KEY: ${BASE64_CONTACT_ENCRYPTION_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: template-service-secrets
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: template-service
    managed-by: kustomize
  annotations:
    encryption.kubernetes.io/v1: aescbc
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # Template storage encryption keys
  TEMPLATE_ENCRYPTION_KEY: ${BASE64_TEMPLATE_ENCRYPTION_KEY}
  
  # Storage service credentials
  MINIO_ACCESS_KEY: ${BASE64_MINIO_ACCESS_KEY}
  MINIO_SECRET_KEY: ${BASE64_MINIO_SECRET_KEY}

---
apiVersion: v1
kind: Secret
metadata:
  name: analytics-service-secrets
  namespace: whatsapp-web-enhancement
  labels:
    app: whatsapp-web-enhancement
    component: analytics-service
    managed-by: kustomize
  annotations:
    encryption.kubernetes.io/v1: aescbc
    vault.hashicorp.com/agent-inject: "true"
type: Opaque
data:
  # Analytics database credentials
  ANALYTICS_DB_PASSWORD: ${BASE64_ANALYTICS_DB_PASSWORD}
  
  # Reporting service API keys
  REPORTING_API_KEY: ${BASE64_REPORTING_API_KEY}