# Loki Configuration v2.9.0
# Enterprise-grade log aggregation system with high availability and security features

auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096
  log_level: info
  http_server_read_timeout: 30s
  http_server_write_timeout: 30s
  grpc_server_max_recv_msg_size: 104857600  # 100MB
  grpc_server_max_send_msg_size: 104857600  # 100MB
  http_server_config:
    tls_config:
      cert_file: /etc/loki/certs/server.crt
      key_file: /etc/loki/certs/server.key
      client_ca_file: /etc/loki/certs/ca.crt

ingester:
  lifecycler:
    ring:
      kvstore:
        store: memberlist
      replication_factor: 3
    final_sleep: 0s
    heartbeat_period: 5s
    join_after: 30s
    min_ready_duration: 1m
  chunk_idle_period: 30m
  max_chunk_age: 2h
  chunk_target_size: 1048576  # 1MB
  chunk_retain_period: 1m
  max_transfer_retries: 10
  wal:
    enabled: true
    dir: /loki/wal
    replay_memory_ceiling: 512MB

schema_config:
  configs:
    - from: "2023-01-01"
      store: boltdb-shipper
      object_store: s3
      schema: v11
      index:
        prefix: whatsapp_web_enhancement_index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: s3
  aws:
    s3:
      bucket_name: whatsapp-web-enhancement-logs
      region: us-east-1
      insecure: false
      sse_encryption: true
      http_config:
        idle_conn_timeout: 90s
        response_header_timeout: 30s
        insecure_skip_verify: false
      s3forcepathstyle: false

limits_config:
  retention_period: 336h  # 14 days
  max_entries_limit_per_query: 5000
  max_query_length: 721h  # 30 days + 1 hour for queries
  max_query_parallelism: 32
  ingestion_rate_mb: 10
  ingestion_burst_size_mb: 20
  per_stream_rate_limit: "5MB"
  per_stream_rate_limit_burst: "10MB"
  max_global_streams_per_user: 5000
  max_line_size: "256kb"
  cardinality_limit: 100000
  creation_grace_period: 10m

table_manager:
  retention_deletes_enabled: true
  retention_period: 336h
  poll_interval: 15m
  creation_grace_period: 1h

compactor:
  working_directory: /loki/compactor
  shared_store: s3
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 150

ruler:
  storage:
    type: s3
    s3:
      bucket_name: whatsapp-web-enhancement-rules
  rule_path: /loki/rules
  alertmanager_url: http://alertmanager:9093
  ring:
    kvstore:
      store: memberlist
  enable_api: true
  enable_alertmanager_v2: true
  evaluation_interval: 1m
  poll_interval: 1m

memberlist:
  join_members:
    - loki-memberlist
  dead_node_reclaim_time: 1h
  gossip_interval: 5s
  gossip_nodes: 3
  retransmit_factor: 3
  packet_dial_timeout: 5s
  packet_write_timeout: 5s

tracing:
  enabled: true
  type: jaeger
  jaeger:
    agent_endpoint: "jaeger-agent:6831"
    sampler_type: ratelimiting
    sampler_param: 10

analytics:
  reporting_enabled: false

common:
  path_prefix: /loki
  replication_factor: 3
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: memberlist

query_range:
  align_queries_with_step: true
  max_retries: 5
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 1073741824  # 1GB
        validity: 24h